Partially Revert Mirrored Images (#635)
This partially reverts commit 9a3e8ada9ea0dbbc4e2fa426947f32221b82629e.
[#633](https://github.com/DataDog/datadog-lambda-extension/pull/633)

Datadog Agent Serverless Integration Tests, Vulnerability Scan, and
Serverless-Init Release Github Workflows are failing due to not being
able to pull the mirrored Datadog images.

Only the images in `scripts`, which are used in Github Workflows are
reverted as part of this PR. Images in `images` used in GitLab CI/CD for
Bottlecap will continue to use the mirrored Datadog images.


https://github.com/DataDog/datadog-agent/actions/runs/14197727594/job/39776831216

```
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: failed to resolve source metadata for registry.ddbuild.io/images/mirror/ubuntu:22.04: failed to do request: Head "https://registry.ddbuild.io/v2/images/mirror/ubuntu/manifests/22.04": dial tcp 172.27.5.68:443: i/o timeout
```